development: &global_settings
  database: ipm_dev
  host: localhost
  port: 27017

test: &TEST
  database: ipm_test
  <<: *global_settings

production:
  database: ipm
  host: localhost
  #username: username
  #password: password
  <<: *global_settings

staging:
  database: ipm_staging
  #username: username
  #password: password
  <<: *global_settings
