development:
  database: ipm2
  host: 174.143.146.138
  #port: 27027
  username: ipm
  password: Fl1ghtL1nk

test: &TEST
  database: ipm2_test
  host: localhost
 
production:
  database: ipm2
  host: 174.143.146.138
  #port: 27027
  username: ipm
  password: Fl1ghtL1nk

#staging:
#  database: ipm_staging
#  #username: username
#  #password: password
#  <<: *global_settings
